### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by ducminhkhoi** [NVIDIA/nvvl#5]
Hi, 

When I try the sample code of Pytorch Dataset as follows:
```
processing = { 
        'input': ProcessDesc(type='half',
                             width=224,
                             height=224)
 }
dataset = nvvl.VideoDataset(filenames, 5, processing=processing)
data_loader = nvvl.VideoLoader(dataset, batch_size=8, shuffle=True)

for data in data_loader:
       # do something with data
```

I have the error: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV) from the function in pytorch/nvvl/dataset.py, arround line 227: 
```
lib.nvvl_read_sequence(self.loader,
                               str.encode(self.filenames[index]),
                               frame, self.sequence_length)
```
Can you help me to fix it?

I use the suggested version of ffmpeg, libx264 and nasm.

Thanks,

**Comment by jbarker-nvidia** [comment]
@ducminhkhoi What GPU and driver are you using?

**Comment by ducminhkhoi** [comment]
@jbarker-nvidia My GPU is 1080Ti and driver is CUDA 9.1, 390.48 (the newest version)

**Comment by jaredcasper** [comment]
Is there any other output from the error?  Can you post any output that doesn't look like normal output from your code (or just the full output if it doesn't have anything from your code you don't want to post)?

How long does it run, does it crash immediately before loading any frames, or after running for a while and successfully loading some frames?

**Comment by ducminhkhoi** [comment]
It does not produce any output. It crashes immediately before loading any frames

**Comment by jaredcasper** [comment]
It must produce some output if you know "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV) from the function in pytorch/nvvl/dataset.py, arround line 227" Is that the complete output?  Can you post the complete output of running the program?

**Comment by ducminhkhoi** [comment]
There is no output. I guess lib.nvvl_read_sequence call a C function, but this C function crashes that makes the whole Python process crash too.

**Comment by jaredcasper** [comment]
If there is not output how do you know there is a segfault down in lib.nvvl_read_sequence?  Sorry to keep pushing on this, just trying to get as much info as possible to try to figure out what is going on.

**Comment by jaredcasper** [comment]
Also can you tell me about your input files, how many files, what codec, container format, video size, etc.?  Looking through the code and I'm not seeing an obvious place it'd segfault in that function.

**Comment by jaredcasper** [comment]
One more thing, will you add the line:
`dataset.set_log_level(nvvl.lib.LogLevel_Debug)`
just after creating the dataset and post any output that results?

**Comment by ducminhkhoi** [comment]
After adding new line as you suggested, I still cannot receive any output. My python file is dataset.py
so I just called it by `python dataset.py`, I get the following result: 
```
loading dataset...

Segmentation fault (core dumped)
```
My input is the Myanmar video download from the suggested website from pytorch flownet2.0SD example.

**Comment by jaredcasper** [comment]
hrm, I see... weird. Where does the line you initially quoted show up (i.e. "Process exited with error code...") or what makes you believe that it is segfaulting in the read_sequence call? Are you familiar enough with gdb to get a back trace from gdb? You might need to build the lib with cmake directly and request a debug build (i.e. `cmake .. -DCMAKE_BUILD_TYPE=Debug`).

I appreciate your help, it's just hard to figure out whats going on without more information (since I can't reproduce it in any environment I've tried).

**Comment by ducminhkhoi** [comment]
I am using Pycharm debugger to jump to which line it crashes. More specifically, after calling read_sequence call, it jumps to the file ffi/__init__.py to the function 

```
def _wrap_function(function, ffi):
    @wraps(function)
    def safe_call(*args, **kwargs):
        args = tuple(ffi.cast(_torch_to_cffi.get(type(arg), 'void') + '*', arg._cdata)
                     if torch.is_tensor(arg) or torch.is_storage(arg)
                     else arg
                     for arg in args)
        args = (function,) + args
        result = torch._C._safe_call(*args, **kwargs) **# This line has problem**
        if isinstance(result, ffi.CData):
            typeof = ffi.typeof(result)
            if typeof.kind == 'pointer':
                cdata = int(ffi.cast('uintptr_t', result))
                cname = typeof.item.cname
                if cname in _cffi_to_torch:
                    return _cffi_to_torch[cname](cdata=cdata)
        return result
    return safe_call
```

**Comment by jaredcasper** [comment]
I see... yeah, I agree the segfault is in the c/c++ library... but without a backtrace to see where in the C code it segfaults it is very difficult to figure out what the problem is (There is a whole lot going on behind that line you point to).  Is your full python script something you could share to try and help me reproduce the problem?

**Comment by ducminhkhoi** [comment]
I just follow the Pytorch example with the Myanmar video and do nothing else. I just provide the list of filenames as input to the VideoDataset. All the information as I provided before.

**Comment by jaredcasper** [comment]
Ok, sorry to be pedantic, I'm just trying to figure out what is different about your setup than mine.  I'm asking if it is possible for you to post your full python source so I can try to run it here.  For example, I have the script:
```
import nvvl
from glob import glob

filenames = glob("/path/to/videos/540p/scenes/train/*.mp4")
processing = {
        'input': nvvl.ProcessDesc(type='half',
                                  width=224,
                                  height=224)
 }
dataset = nvvl.VideoDataset(filenames, 5, processing=processing)
data_loader = nvvl.VideoLoader(dataset, batch_size=8, shuffle=True)

for data in data_loader:
    print(data['input'].size())
```
I run this trying to replicate your environment as you've described as much as I can and it runs fine for me, so there must be something different about your setup. Are you just doing exactly what is written above? Is it possible for you to get a backtrace of your segfault using gdb?

**Comment by ducminhkhoi** [comment]
Here is my `main.py` file:

```
from nvvl import ProcessDesc, VideoDataset, VideoLoader
from glob import glob

if __name__ == '__main__':
    filenames = glob('data/VidVRD-dataset/videos/*.mp4')
    processing = {
        'input': ProcessDesc(type='half',
                             width=224,
                             height=224),
    }

    dataset = VideoDataset(filenames=filenames,
                           sequence_length=5,
                           processing=processing)

    data_loader = VideoLoader(dataset,
                              batch_size=8,
                              shuffle=False)

    for data in data_loader:
        print(data['input'].size())
```

**Comment by jaredcasper** [comment]
Awesome, thank you.  Unfortunately that runs just fine for me. :(  Are you running on raw Myanmar video downloaded from the internet or did you do some processing on it (i.e. did you use the scripts in `/examples/pytorch_superres/tools/` (i.e. `split_scenes.py` and `downsample_scenes.py`))?

Do you know how to use gdb to get a backtrace? That would be very helpful.

**Comment by ducminhkhoi** [comment]
I apply directly the raw video download from the internet without any processing. I am sorry, I don't know how to use gdb but I can try, do you know how to use debug option with `python setup.py install`?

**Comment by jaredcasper** [comment]
Easiest way may be to do a quick edit of setup.py yourself... on line 49 you should find this:
```
        cmake_cmd = ["cmake", "-B"+output_dir, "-H"+nvvl_path]
```
Replace it with this:
````
        cmake_cmd = ["cmake", "-B"+output_dir, "-H"+nvvl_path, "-DCMAKE_BUILD_TYPE=Debug"]
```
then rerun `python setup.py install`. That should build with debug symbols and install the new debug version.  Next, run your script from within gdb:
```
$ gdb --args python main.py
```
That should drop into a `(gdb)` prompt, you can then type `run` and hit enter which should run the code and it should come back into gdb when it segfaults, then run the command `bt` which should print out a backtrace for the current thread. It would also be helpful to run `info threads` in gdb and look at the other threads.  Many of them will look the same, but any that look different you can get the backtrace there by seeing which thread number it is and running `thread <#>`, like `thread 3` for thread #3, then run `bt` again.  If you could post the backtrace of the thread that it stops on, the output of `info threads` and the backtrace of any other threads that look interesting, that would be super helpful.

Hopefully all that makes sense.  I really appreciate you helping track this down. I wish I could manage to reproduce it here!

**Comment by ducminhkhoi** [comment]
Here is the result:
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffb227e06b in NVVL::VideoLoader::impl::read_sequence (this=0x55555687b700, filename=..., frame=0, count=5) at /home/khoinguyen/PycharmProjects/VidVRD/libs/nvvl/src/VideoLoader.cpp:191
191         vid_decoder_->push_req(std::move(req));

```

**Comment by jaredcasper** [comment]
Very helpful, thank you! I think I see what the problem might be, let me get back to you after I've pushed some changes and a bit more logging and hopefully we'll get this fixed soon. Thanks for your patience!

**Comment by jaredcasper** [comment]
I just pushed some changes that might fix your segfault, but should at least give us some better information about what is going on.  Please pull the latest changes, recompile/install, and give it a go.

You can now set the log level in the VideoDataset using a string, so if things still don't work, please run it passing `log_level="debug"` to the VideoDataset constructor (and ditch the call to `dataset.set_log_level()`) and post the results.

Thanks!

**Comment by ducminhkhoi** [comment]
Hi Jared, 

After following your guide to pull and recompile, I still have problem with it, here is my bt:

(gdb) run dataset_temp.py
Starting program: /home/khoinguyen/miniconda3/envs/VidVRD/bin/python dataset_temp.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
loading dataset...

[New Thread 0x7fff90e77700 (LWP 9871)]
Opening file data/VidVRD-dataset/prepared.mp4
Opened the first file, creating a video decoder
[New Thread 0x7fff8a676700 (LWP 9874)]
[New Thread 0x7fff89e75700 (LWP 9875)]
[New Thread 0x7fff891ff700 (LWP 9876)]
Using device: GeForce GTX 1080 Ti
Kernel module version 390.48, so using our own stream.

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
__memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:114
114     ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7ffff7fc9700 (LWP 9864) "python" __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:114
  2    Thread 0x7fff90e77700 (LWP 9871) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7fff8a676700 (LWP 9874) "python" 0x00007ffff78f88c8 in accept4 (fd=14, addr=..., addr_len=0x7fff8a675e68, flags=524288) at ../sysdeps/unix/sysv/linux/accept4.c:40
  4    Thread 0x7fff89e75700 (LWP 9875) "python" 0x00007ffff78eb74d in poll () at ../sysdeps/unix/syscall-template.S:84
  5    Thread 0x7fff891ff700 (LWP 9876) "python" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
(gdb) thread 1
[Switching to thread 1 (Thread 0x7ffff7fc9700 (LWP 9864))]
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:114
114     in ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S
(gdb)  bt
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:114
#1  0x00007fffb22a6587 in NVVL::detail::CUVideoParser::init_params<NVVL::detail::NvDecoder> (this=0x7fffffffbee0, codec=NVVL::detail::Codec::H264, decoder=0x555556a9ef90, decode_surfaces=20, 
    extradata=0x10000002a <error: Cannot access memory at address 0x10000002a>, extradata_size=60) at /home/khoinguyen/PycharmProjects/VidVRD/libs/nvvl/src/detail/CUVideoParser.h:67
#2  0x00007fffb22a5853 in NVVL::detail::CUVideoParser::CUVideoParser<NVVL::detail::NvDecoder> (this=0x7fffffffbee0, codec=NVVL::detail::Codec::H264, decoder=0x555556a9ef90, decode_surfaces=20, 
    extradata=0x10000002a <error: Cannot access memory at address 0x10000002a>, extradata_size=60) at /home/khoinguyen/PycharmProjects/VidVRD/libs/nvvl/src/detail/CUVideoParser.h:30
#3  0x00007fffb22a20a0 in NVVL::detail::NvDecoder::NvDecoder (this=0x555556a9ef90, device_id=0, logger=..., codecpar=0x555556a9d440, time_base=...)
    at /home/khoinguyen/PycharmProjects/VidVRD/libs/nvvl/src/detail/NvDecoder.cpp:119
#4  0x00007fffb2272d8a in NVVL::VideoLoader::impl::get_or_open_file (this=0x555556a8c5d0, filename=...) at /home/khoinguyen/PycharmProjects/VidVRD/libs/nvvl/src/VideoLoader.cpp:248
#5  0x00007fffb2272544 in NVVL::VideoLoader::impl::frame_count (this=0x555556a8c5d0, filename=...) at /home/khoinguyen/PycharmProjects/VidVRD/libs/nvvl/src/VideoLoader.cpp:179
#6  0x00007fffb22724b7 in NVVL::VideoLoader::frame_count (this=0x5555567f4420, filename=...) at /home/khoinguyen/PycharmProjects/VidVRD/libs/nvvl/src/VideoLoader.cpp:175
#7  0x00007fffb22750e2 in nvvl_frame_count (loader=0x5555567f4420, filename=0x7fff90ee15a8 "data/VidVRD-dataset/prepared.mp4")
    at /home/khoinguyen/PycharmProjects/VidVRD/libs/nvvl/src/VideoLoader.cpp:637
#8  0x00007fffb24fb4ec in _cffi_f_nvvl_frame_count (self=<optimized out>, args=<optimized out>) at build/temp.linux-x86_64-3.6/nvvl.lib._lib.c:1048
#9  0x0000555555665871 in PyCFunction_Call ()
#10 0x00005555556625ce in PyObject_Call ()
#11 0x00007fffe638bffc in THPModule_safeCall (_unused=<optimized out>, args=0x7fff90ee1558, kwargs=0x7fff90e7fca8) at torch/csrc/Module.cpp:441
#12 0x0000555555665806 in PyCFunction_Call ()
#13 0x000055555571961c in _PyEval_EvalFrameDefault ()
---Type <return> to continue, or q <return> to quit---
#14 0x00005555556e94ce in _PyEval_EvalCodeWithName ()
#15 0x00005555556ea0e1 in fast_function ()
#16 0x00005555556f01e5 in call_function ()
#17 0x000055555571441a in _PyEval_EvalFrameDefault ()
#18 0x00005555556e90a6 in _PyEval_EvalCodeWithName ()
#19 0x00005555556ea7db in _PyFunction_FastCallDict ()
#20 0x0000555555662b8f in _PyObject_FastCallDict ()
#21 0x0000555555667773 in _PyObject_Call_Prepend ()
#22 0x00005555556625ce in PyObject_Call ()
#23 0x00005555556bd96b in slot_tp_init ()
#24 0x00005555556f0447 in type_call ()
#25 0x00005555556629ab in _PyObject_FastCallDict ()
#26 0x00005555556ea3ca in _PyObject_FastCallKeywords ()
#27 0x00005555556f025e in call_function ()
#28 0x00005555557151cb in _PyEval_EvalFrameDefault ()
#29 0x00005555556eabf9 in PyEval_EvalCodeEx ()
#30 0x00005555556eb99c in PyEval_EvalCode ()
#31 0x0000555555767e44 in run_mod ()
---Type <return> to continue, or q <return> to quit---
#32 0x0000555555768241 in PyRun_FileExFlags ()
#33 0x0000555555768444 in PyRun_SimpleFileExFlags ()
#34 0x000055555576bf78 in Py_Main ()
#35 0x0000555555633efe in main ()
(gdb)

**Comment by jaredcasper** [comment]
Thank Khoi,

Well, at least it moved. :)  Based on this backtrace it seems something funny is going on with the ffmpeg libraries since they are providing bad pointers.  Can you confirm that you are using ffmpeg version 3.4.2?  How did you install it? Also, are there multiple version of the ffmpeg libraries installed on your system? Maybe one from apt and one you built from source? I've seen weird bugs like this happen when a program gets linked against one version at runtime, then a different version of the library gets loaded at runtime (even though the library versioning is supposed to prevent that, it doesn't always work).  If you do have two version installed, can you completely remove/uninstall the older and give it a go?  One thing you can do to check is find the libnvvl.so in your python install directories and run `ldd` on it. Something like this:
```
ldd /long/path/to/python/lib64/python3.6/site-packages/nvvl-1.0-py3.6-linux-x86_64.egg/nvvl/lib/libnvvl.so | grep libav
```
That should show you what ffmpeg libraries are getting loaded at runtime, which should match what you expect given how you install ffmpeg 3.4.2 in the first place.  For me I get:
```
	libavformat.so.57 => /usr/local/lib/libavformat.so.57 (0x00007fa9808dd000)
	libavcodec.so.57 => /usr/local/lib/libavcodec.so.57 (0x00007fa980432000)
	libavutil.so.55 => /usr/local/lib/libavutil.so.55 (0x00007fa9801b2000)
```

Can you check those things out and confirm that you only have one version of ffmpeg installed and what version it is?

**Comment by ducminhkhoi** [comment]
Thank you so much @jaredcasper, I followed your suggestion and removed other ffmpeg installations and it worked!

**Comment by jaredcasper** [comment]
Whew! That was a sneaky one!  Thanks for letting me know it works now.

**Comment by ivanColucci** [comment]
I was using "pygmo", more in particular the PSO algorithm. I defined my own problem and both the problem and the set of instructions to start the evolution were in the same file. I solved the same error by coding the problem in its own .py file and now everything is fine! I hope it's helpful!
